# -*- coding: utf-8 -*-
"""Mall_Customers_using_KMEANS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WY06PBs8keICz_3M4F9Lnuuio9fzKHoJ
"""

!pip install pandas numpy matplotlib seaborn scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Mall_Customers.csv")
df.head()

df.isna().sum()

df.drop(['CustomerID','Gender'], axis=1, inplace=True)

df.head(10)

plt.scatter(df['Age'],df['Annual Income (k$)'])
plt.xlabel('Age')
plt.ylabel('Annual Income (k$)')
plt.show()

sns.lineplot(x=df['Age'],y=df['Spending Score (1-100)'])

sns.pairplot(df,hue='Spending Score (1-100)')

plt.bar(df['Annual Income (k$)'],df['Spending Score (1-100)'])

kmeans=KMeans(n_clusters=5)
kmeans.fit(df)

labels=kmeans.labels_
centroids=kmeans.cluster_centers_

y=kmeans.fit_predict(df)
y

plt.scatter(df['Annual Income (k$)'], df['Spending Score (1-100)'], c=labels, cmap='viridis')
plt.scatter(centroids[:, 1], centroids[:, 2], s=300, c='red', marker='X') # Plot centroids
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('K-Means Clustering')
plt.show()